# Generated by Django 4.0.5 on 2022-06-13 11:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='dob',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
