# Generated by Django 4.0.2 on 2022-06-27 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_member_role_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='adhaar',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
