# Generated by Django 4.0.5 on 2022-06-13 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_members_dob'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='members',
            table='member',
        ),
    ]
