# Generated by Django 4.0.2 on 2022-06-28 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_member_adhaar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='adhaar',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
