# Generated by Django 4.0.5 on 2022-06-13 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_members_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='members',
            new_name='abc',
        ),
    ]
