# Generated by Django 4.0.2 on 2022-06-29 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_member_adhaar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_img', models.ImageField(upload_to='media/Jobs_Img')),
                ('job_name', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('job_loaction', models.CharField(max_length=100)),
                ('min_sallery', models.IntegerField()),
                ('max_sallery', models.IntegerField()),
                ('Vacancy', models.IntegerField()),
                ('date', models.DateField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employee')),
            ],
        ),
    ]
