# Generated by Django 4.0.2 on 2022-06-29 10:25

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_des',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='job_experience',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='job_skill',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
    ]
