# Generated by Django 4.0.5 on 2022-06-13 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_abc_member_alter_member_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='member',
            new_name='abc',
        ),
        migrations.AlterModelTable(
            name='abc',
            table=None,
        ),
    ]
