# Generated by Django 4.0.2 on 2022-06-29 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_job_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='job_loaction',
            new_name='job_location',
        ),
    ]
