# Generated by Django 4.0.2 on 2022-06-29 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_job_loaction_job_job_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='salary',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='job_img',
            field=models.ImageField(upload_to='Jobs_Img'),
        ),
    ]
