# Generated by Django 4.0.2 on 2022-06-29 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_job_salary_alter_job_job_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
