# Generated by Django 4.0.2 on 2022-06-30 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_job_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='adhaar',
        ),
    ]
