# Generated by Django 4.0.2 on 2022-07-01 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_center'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('center_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.center')),
            ],
        ),
    ]
